on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    name: Run Fecal Tests
    steps:
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: latest

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install & Check Haxe
        run: haxe -version

      - name: Install Reflaxe
        run: haxelib git reflaxe https://github.com/SomeRanDev/reflaxe.git

      - name: Install Fecal
        run: haxelib git fecal https://github.com/SomeRanDev/fecal.git

      - name: Run Tests
        working-directory: test
        run: haxe Test.hxml
